name: Validate terraform infrastructure

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./environments/prod 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-session-token: ${{ secrets.SESSION_TOKEN }} 

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3

      - name: Load providers and modules
        run: terraform init

      - name: Validate .tf files
        run: terraform validate

      - name: Validate direct with the providers if the changes are valid
        run: terraform plan 
